#!/bin/bash

APP_CLIENT_ID="YOUR_COGNITO_CLIENT_ID"
APP_CLIENT_SECRET="YOUR_COGNITO_CLIENT_SECRET"

USERNAME="YOUR_USERNAME"

COMPUTED_HASH=$(echo -n "${USERNAME}${APP_CLIENT_ID}" | openssl dgst -sha256 -hmac ${APP_CLIENT_SECRET} -binary | openssl enc -base64)

echo $COMPUTED_HASH
